const LeadAccountID = "data-intern-2"
const IS_DEV = true

const NICHES = [
    "Fashion / Beauty",
    "Lifestyle Vlogs",
    "Food",
    "Travel",
    "Fun / Comedy",
    "Fitness",
    "Gaming",
    "Motivational",
    "Finance",
    "Education",
    "Business",
    "Photography",
    "Cooking",
    "Art",
    "Music",
    "Dance",
    "Film / TV",
    "Sports",
    "Automobile",
    "Meme",
    "Quote Pages",
    "Parenting",
    "Health",
    "Tech",
    "Pets",
    "Dogs",
    "Cats",
    "NSFW",
    "Short Story",
    "Storytelling",
    "Kids",
    "Others",
];

